### ISSUE TITLE
Powah adapters

### ISSUE THREAD

**Issue by cyberbit** [cyberbit/telem#61]
> "POWAH"
> _someone, probably_

I am yet unsure what versions have CC compatibility, in my testing on 1.18 I could not detect any peripherals.

- [x] Energy Cell
- [x] Furnator
- [x] Magmator
- [x] Reactor
- [x] Solar Panel
- [x] Thermo Generator

**Comment by bananasov** [comment]
**POWAH**

with Advanced Peripherals, 1.19.2 and above are supported
