### ISSUE TITLE
Setup broken on Enigmatica 2

### ISSUE THREAD

**Issue by dko1905** [cyberbit/telem#76]
# Broken installer
The installer downloades the files (`telem/init.lua` and `telem/vendor.lua`) but they are empty.

## Version info
- Forge 14.23.5.2860
- Java openjdk-1.8.0.422.b06-2.fc40.x86_64
- Exact same CC:Tweaked jar as E2:E
- Latest `https://pinestore.cc/d/14` download (as of 2024-11-03) 
  With the `Release (minify)` / `v0.8.0`

## How to reproduce
1. Download mods using the version info or download Enigmatica 2: Expert (version 1.90h).
2. Run installer `wget run https://pinestore.cc/d/14`
3. Select version
4. Run `edit telem/init.lua` or `edit telem/vendor.lua`
    Both files are empty and interacting using `require` in lua fails.

**Comment by cyberbit** [comment]
Hmm... I have only done limited testing on 1.12. I will take a look into this, thank you for the report!

**Comment by cyberbit** [comment]
Installer is updated and tested working in E2:E. As I said before, I've only done limited testing of adapters/middleware/etc. in 1.12, but something very basic is working as expected.

![image](https://github.com/user-attachments/assets/1dc3c8d2-262b-4137-b64d-0e0017f0273d)

Please don't hesitate to open another issue if you find other broken things!
